import { describe, expect, test } from "vitest";

import * as allPg from "../src/pg";
import { getTableColumns } from "drizzle-orm";

describe.concurrent("pg", () => {
  test("pg - export names", () => {
    expect(Object.keys(allPg)).toEqual(["zeroSchema", "zeroSchemaVersions"]);

    expect(getTableColumns(allPg.zeroSchemaVersions)).toMatchInlineSnapshot(`
      {
        "lock": PgBoolean {
          "columnType": "PgBoolean",
          "config": {
            "columnType": "PgBoolean",
            "dataType": "boolean",
            "default": true,
            "generated": undefined,
            "hasDefault": true,
            "isUnique": false,
            "keyAsName": false,
            "name": "lock",
            "notNull": true,
            "primaryKey": true,
            "uniqueName": "schemaVersions_lock_unique",
            "uniqueType": undefined,
          },
          "dataType": "boolean",
          "default": true,
          "defaultFn": undefined,
          "enumValues": undefined,
          "generated": undefined,
          "generatedIdentity": undefined,
          "hasDefault": true,
          "isUnique": false,
          "keyAsName": false,
          "name": "lock",
          "notNull": true,
          "onUpdateFn": undefined,
          "primary": true,
          "table": PgTable {
            "enableRLS": [Function],
            "lock": [Circular],
            "maxSupportedVersion": PgInteger {
              "columnType": "PgInteger",
              "config": {
                "columnType": "PgInteger",
                "dataType": "number",
                "default": undefined,
                "generated": undefined,
                "hasDefault": false,
                "isUnique": false,
                "keyAsName": false,
                "name": "maxSupportedVersion",
                "notNull": false,
                "primaryKey": false,
                "uniqueName": "schemaVersions_maxSupportedVersion_unique",
                "uniqueType": undefined,
              },
              "dataType": "number",
              "default": undefined,
              "defaultFn": undefined,
              "enumValues": undefined,
              "generated": undefined,
              "generatedIdentity": undefined,
              "hasDefault": false,
              "isUnique": false,
              "keyAsName": false,
              "name": "maxSupportedVersion",
              "notNull": false,
              "onUpdateFn": undefined,
              "primary": false,
              "table": [Circular],
              "uniqueName": "schemaVersions_maxSupportedVersion_unique",
              "uniqueType": undefined,
            },
            "minSupportedVersion": PgInteger {
              "columnType": "PgInteger",
              "config": {
                "columnType": "PgInteger",
                "dataType": "number",
                "default": undefined,
                "generated": undefined,
                "hasDefault": false,
                "isUnique": false,
                "keyAsName": false,
                "name": "minSupportedVersion",
                "notNull": false,
                "primaryKey": false,
                "uniqueName": "schemaVersions_minSupportedVersion_unique",
                "uniqueType": undefined,
              },
              "dataType": "number",
              "default": undefined,
              "defaultFn": undefined,
              "enumValues": undefined,
              "generated": undefined,
              "generatedIdentity": undefined,
              "hasDefault": false,
              "isUnique": false,
              "keyAsName": false,
              "name": "minSupportedVersion",
              "notNull": false,
              "onUpdateFn": undefined,
              "primary": false,
              "table": [Circular],
              "uniqueName": "schemaVersions_minSupportedVersion_unique",
              "uniqueType": undefined,
            },
            Symbol(drizzle:Name): "schemaVersions",
            Symbol(drizzle:OriginalName): "schemaVersions",
            Symbol(drizzle:Schema): "zero",
            Symbol(drizzle:Columns): [Circular],
            Symbol(drizzle:ExtraConfigColumns): {
              "lock": ExtraConfigColumn {
                "columnType": "PgBoolean",
                "config": {
                  "columnType": "PgBoolean",
                  "dataType": "boolean",
                  "default": true,
                  "generated": undefined,
                  "hasDefault": true,
                  "isUnique": false,
                  "keyAsName": false,
                  "name": "lock",
                  "notNull": true,
                  "primaryKey": true,
                  "uniqueName": "schemaVersions_lock_unique",
                  "uniqueType": undefined,
                },
                "dataType": "boolean",
                "default": true,
                "defaultConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "defaultFn": undefined,
                "enumValues": undefined,
                "generated": undefined,
                "generatedIdentity": undefined,
                "hasDefault": true,
                "indexConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "isUnique": false,
                "keyAsName": false,
                "name": "lock",
                "notNull": true,
                "onUpdateFn": undefined,
                "primary": true,
                "table": [Circular],
                "uniqueName": "schemaVersions_lock_unique",
                "uniqueType": undefined,
              },
              "maxSupportedVersion": ExtraConfigColumn {
                "columnType": "PgInteger",
                "config": {
                  "columnType": "PgInteger",
                  "dataType": "number",
                  "default": undefined,
                  "generated": undefined,
                  "hasDefault": false,
                  "isUnique": false,
                  "keyAsName": false,
                  "name": "maxSupportedVersion",
                  "notNull": false,
                  "primaryKey": false,
                  "uniqueName": "schemaVersions_maxSupportedVersion_unique",
                  "uniqueType": undefined,
                },
                "dataType": "number",
                "default": undefined,
                "defaultConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "defaultFn": undefined,
                "enumValues": undefined,
                "generated": undefined,
                "generatedIdentity": undefined,
                "hasDefault": false,
                "indexConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "isUnique": false,
                "keyAsName": false,
                "name": "maxSupportedVersion",
                "notNull": false,
                "onUpdateFn": undefined,
                "primary": false,
                "table": [Circular],
                "uniqueName": "schemaVersions_maxSupportedVersion_unique",
                "uniqueType": undefined,
              },
              "minSupportedVersion": ExtraConfigColumn {
                "columnType": "PgInteger",
                "config": {
                  "columnType": "PgInteger",
                  "dataType": "number",
                  "default": undefined,
                  "generated": undefined,
                  "hasDefault": false,
                  "isUnique": false,
                  "keyAsName": false,
                  "name": "minSupportedVersion",
                  "notNull": false,
                  "primaryKey": false,
                  "uniqueName": "schemaVersions_minSupportedVersion_unique",
                  "uniqueType": undefined,
                },
                "dataType": "number",
                "default": undefined,
                "defaultConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "defaultFn": undefined,
                "enumValues": undefined,
                "generated": undefined,
                "generatedIdentity": undefined,
                "hasDefault": false,
                "indexConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "isUnique": false,
                "keyAsName": false,
                "name": "minSupportedVersion",
                "notNull": false,
                "onUpdateFn": undefined,
                "primary": false,
                "table": [Circular],
                "uniqueName": "schemaVersions_minSupportedVersion_unique",
                "uniqueType": undefined,
              },
            },
            Symbol(drizzle:BaseName): "schemaVersions",
            Symbol(drizzle:IsAlias): false,
            Symbol(drizzle:IsDrizzleTable): true,
            Symbol(drizzle:ExtraConfigBuilder): [Function],
            Symbol(drizzle:PgInlineForeignKeys): [],
            Symbol(drizzle:EnableRLS): false,
          },
          "uniqueName": "schemaVersions_lock_unique",
          "uniqueType": undefined,
        },
        "maxSupportedVersion": PgInteger {
          "columnType": "PgInteger",
          "config": {
            "columnType": "PgInteger",
            "dataType": "number",
            "default": undefined,
            "generated": undefined,
            "hasDefault": false,
            "isUnique": false,
            "keyAsName": false,
            "name": "maxSupportedVersion",
            "notNull": false,
            "primaryKey": false,
            "uniqueName": "schemaVersions_maxSupportedVersion_unique",
            "uniqueType": undefined,
          },
          "dataType": "number",
          "default": undefined,
          "defaultFn": undefined,
          "enumValues": undefined,
          "generated": undefined,
          "generatedIdentity": undefined,
          "hasDefault": false,
          "isUnique": false,
          "keyAsName": false,
          "name": "maxSupportedVersion",
          "notNull": false,
          "onUpdateFn": undefined,
          "primary": false,
          "table": PgTable {
            "enableRLS": [Function],
            "lock": PgBoolean {
              "columnType": "PgBoolean",
              "config": {
                "columnType": "PgBoolean",
                "dataType": "boolean",
                "default": true,
                "generated": undefined,
                "hasDefault": true,
                "isUnique": false,
                "keyAsName": false,
                "name": "lock",
                "notNull": true,
                "primaryKey": true,
                "uniqueName": "schemaVersions_lock_unique",
                "uniqueType": undefined,
              },
              "dataType": "boolean",
              "default": true,
              "defaultFn": undefined,
              "enumValues": undefined,
              "generated": undefined,
              "generatedIdentity": undefined,
              "hasDefault": true,
              "isUnique": false,
              "keyAsName": false,
              "name": "lock",
              "notNull": true,
              "onUpdateFn": undefined,
              "primary": true,
              "table": [Circular],
              "uniqueName": "schemaVersions_lock_unique",
              "uniqueType": undefined,
            },
            "maxSupportedVersion": [Circular],
            "minSupportedVersion": PgInteger {
              "columnType": "PgInteger",
              "config": {
                "columnType": "PgInteger",
                "dataType": "number",
                "default": undefined,
                "generated": undefined,
                "hasDefault": false,
                "isUnique": false,
                "keyAsName": false,
                "name": "minSupportedVersion",
                "notNull": false,
                "primaryKey": false,
                "uniqueName": "schemaVersions_minSupportedVersion_unique",
                "uniqueType": undefined,
              },
              "dataType": "number",
              "default": undefined,
              "defaultFn": undefined,
              "enumValues": undefined,
              "generated": undefined,
              "generatedIdentity": undefined,
              "hasDefault": false,
              "isUnique": false,
              "keyAsName": false,
              "name": "minSupportedVersion",
              "notNull": false,
              "onUpdateFn": undefined,
              "primary": false,
              "table": [Circular],
              "uniqueName": "schemaVersions_minSupportedVersion_unique",
              "uniqueType": undefined,
            },
            Symbol(drizzle:Name): "schemaVersions",
            Symbol(drizzle:OriginalName): "schemaVersions",
            Symbol(drizzle:Schema): "zero",
            Symbol(drizzle:Columns): [Circular],
            Symbol(drizzle:ExtraConfigColumns): {
              "lock": ExtraConfigColumn {
                "columnType": "PgBoolean",
                "config": {
                  "columnType": "PgBoolean",
                  "dataType": "boolean",
                  "default": true,
                  "generated": undefined,
                  "hasDefault": true,
                  "isUnique": false,
                  "keyAsName": false,
                  "name": "lock",
                  "notNull": true,
                  "primaryKey": true,
                  "uniqueName": "schemaVersions_lock_unique",
                  "uniqueType": undefined,
                },
                "dataType": "boolean",
                "default": true,
                "defaultConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "defaultFn": undefined,
                "enumValues": undefined,
                "generated": undefined,
                "generatedIdentity": undefined,
                "hasDefault": true,
                "indexConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "isUnique": false,
                "keyAsName": false,
                "name": "lock",
                "notNull": true,
                "onUpdateFn": undefined,
                "primary": true,
                "table": [Circular],
                "uniqueName": "schemaVersions_lock_unique",
                "uniqueType": undefined,
              },
              "maxSupportedVersion": ExtraConfigColumn {
                "columnType": "PgInteger",
                "config": {
                  "columnType": "PgInteger",
                  "dataType": "number",
                  "default": undefined,
                  "generated": undefined,
                  "hasDefault": false,
                  "isUnique": false,
                  "keyAsName": false,
                  "name": "maxSupportedVersion",
                  "notNull": false,
                  "primaryKey": false,
                  "uniqueName": "schemaVersions_maxSupportedVersion_unique",
                  "uniqueType": undefined,
                },
                "dataType": "number",
                "default": undefined,
                "defaultConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "defaultFn": undefined,
                "enumValues": undefined,
                "generated": undefined,
                "generatedIdentity": undefined,
                "hasDefault": false,
                "indexConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "isUnique": false,
                "keyAsName": false,
                "name": "maxSupportedVersion",
                "notNull": false,
                "onUpdateFn": undefined,
                "primary": false,
                "table": [Circular],
                "uniqueName": "schemaVersions_maxSupportedVersion_unique",
                "uniqueType": undefined,
              },
              "minSupportedVersion": ExtraConfigColumn {
                "columnType": "PgInteger",
                "config": {
                  "columnType": "PgInteger",
                  "dataType": "number",
                  "default": undefined,
                  "generated": undefined,
                  "hasDefault": false,
                  "isUnique": false,
                  "keyAsName": false,
                  "name": "minSupportedVersion",
                  "notNull": false,
                  "primaryKey": false,
                  "uniqueName": "schemaVersions_minSupportedVersion_unique",
                  "uniqueType": undefined,
                },
                "dataType": "number",
                "default": undefined,
                "defaultConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "defaultFn": undefined,
                "enumValues": undefined,
                "generated": undefined,
                "generatedIdentity": undefined,
                "hasDefault": false,
                "indexConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "isUnique": false,
                "keyAsName": false,
                "name": "minSupportedVersion",
                "notNull": false,
                "onUpdateFn": undefined,
                "primary": false,
                "table": [Circular],
                "uniqueName": "schemaVersions_minSupportedVersion_unique",
                "uniqueType": undefined,
              },
            },
            Symbol(drizzle:BaseName): "schemaVersions",
            Symbol(drizzle:IsAlias): false,
            Symbol(drizzle:IsDrizzleTable): true,
            Symbol(drizzle:ExtraConfigBuilder): [Function],
            Symbol(drizzle:PgInlineForeignKeys): [],
            Symbol(drizzle:EnableRLS): false,
          },
          "uniqueName": "schemaVersions_maxSupportedVersion_unique",
          "uniqueType": undefined,
        },
        "minSupportedVersion": PgInteger {
          "columnType": "PgInteger",
          "config": {
            "columnType": "PgInteger",
            "dataType": "number",
            "default": undefined,
            "generated": undefined,
            "hasDefault": false,
            "isUnique": false,
            "keyAsName": false,
            "name": "minSupportedVersion",
            "notNull": false,
            "primaryKey": false,
            "uniqueName": "schemaVersions_minSupportedVersion_unique",
            "uniqueType": undefined,
          },
          "dataType": "number",
          "default": undefined,
          "defaultFn": undefined,
          "enumValues": undefined,
          "generated": undefined,
          "generatedIdentity": undefined,
          "hasDefault": false,
          "isUnique": false,
          "keyAsName": false,
          "name": "minSupportedVersion",
          "notNull": false,
          "onUpdateFn": undefined,
          "primary": false,
          "table": PgTable {
            "enableRLS": [Function],
            "lock": PgBoolean {
              "columnType": "PgBoolean",
              "config": {
                "columnType": "PgBoolean",
                "dataType": "boolean",
                "default": true,
                "generated": undefined,
                "hasDefault": true,
                "isUnique": false,
                "keyAsName": false,
                "name": "lock",
                "notNull": true,
                "primaryKey": true,
                "uniqueName": "schemaVersions_lock_unique",
                "uniqueType": undefined,
              },
              "dataType": "boolean",
              "default": true,
              "defaultFn": undefined,
              "enumValues": undefined,
              "generated": undefined,
              "generatedIdentity": undefined,
              "hasDefault": true,
              "isUnique": false,
              "keyAsName": false,
              "name": "lock",
              "notNull": true,
              "onUpdateFn": undefined,
              "primary": true,
              "table": [Circular],
              "uniqueName": "schemaVersions_lock_unique",
              "uniqueType": undefined,
            },
            "maxSupportedVersion": PgInteger {
              "columnType": "PgInteger",
              "config": {
                "columnType": "PgInteger",
                "dataType": "number",
                "default": undefined,
                "generated": undefined,
                "hasDefault": false,
                "isUnique": false,
                "keyAsName": false,
                "name": "maxSupportedVersion",
                "notNull": false,
                "primaryKey": false,
                "uniqueName": "schemaVersions_maxSupportedVersion_unique",
                "uniqueType": undefined,
              },
              "dataType": "number",
              "default": undefined,
              "defaultFn": undefined,
              "enumValues": undefined,
              "generated": undefined,
              "generatedIdentity": undefined,
              "hasDefault": false,
              "isUnique": false,
              "keyAsName": false,
              "name": "maxSupportedVersion",
              "notNull": false,
              "onUpdateFn": undefined,
              "primary": false,
              "table": [Circular],
              "uniqueName": "schemaVersions_maxSupportedVersion_unique",
              "uniqueType": undefined,
            },
            "minSupportedVersion": [Circular],
            Symbol(drizzle:Name): "schemaVersions",
            Symbol(drizzle:OriginalName): "schemaVersions",
            Symbol(drizzle:Schema): "zero",
            Symbol(drizzle:Columns): [Circular],
            Symbol(drizzle:ExtraConfigColumns): {
              "lock": ExtraConfigColumn {
                "columnType": "PgBoolean",
                "config": {
                  "columnType": "PgBoolean",
                  "dataType": "boolean",
                  "default": true,
                  "generated": undefined,
                  "hasDefault": true,
                  "isUnique": false,
                  "keyAsName": false,
                  "name": "lock",
                  "notNull": true,
                  "primaryKey": true,
                  "uniqueName": "schemaVersions_lock_unique",
                  "uniqueType": undefined,
                },
                "dataType": "boolean",
                "default": true,
                "defaultConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "defaultFn": undefined,
                "enumValues": undefined,
                "generated": undefined,
                "generatedIdentity": undefined,
                "hasDefault": true,
                "indexConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "isUnique": false,
                "keyAsName": false,
                "name": "lock",
                "notNull": true,
                "onUpdateFn": undefined,
                "primary": true,
                "table": [Circular],
                "uniqueName": "schemaVersions_lock_unique",
                "uniqueType": undefined,
              },
              "maxSupportedVersion": ExtraConfigColumn {
                "columnType": "PgInteger",
                "config": {
                  "columnType": "PgInteger",
                  "dataType": "number",
                  "default": undefined,
                  "generated": undefined,
                  "hasDefault": false,
                  "isUnique": false,
                  "keyAsName": false,
                  "name": "maxSupportedVersion",
                  "notNull": false,
                  "primaryKey": false,
                  "uniqueName": "schemaVersions_maxSupportedVersion_unique",
                  "uniqueType": undefined,
                },
                "dataType": "number",
                "default": undefined,
                "defaultConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "defaultFn": undefined,
                "enumValues": undefined,
                "generated": undefined,
                "generatedIdentity": undefined,
                "hasDefault": false,
                "indexConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "isUnique": false,
                "keyAsName": false,
                "name": "maxSupportedVersion",
                "notNull": false,
                "onUpdateFn": undefined,
                "primary": false,
                "table": [Circular],
                "uniqueName": "schemaVersions_maxSupportedVersion_unique",
                "uniqueType": undefined,
              },
              "minSupportedVersion": ExtraConfigColumn {
                "columnType": "PgInteger",
                "config": {
                  "columnType": "PgInteger",
                  "dataType": "number",
                  "default": undefined,
                  "generated": undefined,
                  "hasDefault": false,
                  "isUnique": false,
                  "keyAsName": false,
                  "name": "minSupportedVersion",
                  "notNull": false,
                  "primaryKey": false,
                  "uniqueName": "schemaVersions_minSupportedVersion_unique",
                  "uniqueType": undefined,
                },
                "dataType": "number",
                "default": undefined,
                "defaultConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "defaultFn": undefined,
                "enumValues": undefined,
                "generated": undefined,
                "generatedIdentity": undefined,
                "hasDefault": false,
                "indexConfig": {
                  "nulls": "last",
                  "opClass": undefined,
                  "order": "asc",
                },
                "isUnique": false,
                "keyAsName": false,
                "name": "minSupportedVersion",
                "notNull": false,
                "onUpdateFn": undefined,
                "primary": false,
                "table": [Circular],
                "uniqueName": "schemaVersions_minSupportedVersion_unique",
                "uniqueType": undefined,
              },
            },
            Symbol(drizzle:BaseName): "schemaVersions",
            Symbol(drizzle:IsAlias): false,
            Symbol(drizzle:IsDrizzleTable): true,
            Symbol(drizzle:ExtraConfigBuilder): [Function],
            Symbol(drizzle:PgInlineForeignKeys): [],
            Symbol(drizzle:EnableRLS): false,
          },
          "uniqueName": "schemaVersions_minSupportedVersion_unique",
          "uniqueType": undefined,
        },
      }
    `);
  });
});
