import {
  Project,
  VariableDeclarationKind,
  type ExportedDeclarations,
} from "ts-morph";

export async function getZeroSchemaDefsFromConfig({
  tsProject,
  configPath,
  exportName,
}: {
  tsProject: Project;
  configPath: string;
  exportName: string;
}) {
  const fileName = configPath.slice(configPath.lastIndexOf("/") + 1);

  const sourceFile = tsProject.getSourceFile(fileName);

  if (!sourceFile) {
    throw new Error(
      `❌ drizzle-zero: Failed to find type definitions for ${fileName}`,
    );
  }

  const exportDeclarations = sourceFile.getExportedDeclarations();

  for (const [name, declarations] of exportDeclarations.entries()) {
    for (const declaration of declarations) {
      if (exportName === name) {
        return [name, declaration] as const;
      }
    }
  }

  throw new Error(
    `❌ drizzle-zero: No config type found in the config file - did you export \`default\` or \`schema\`? Found: ${sourceFile
      .getVariableDeclarations()
      .map((v) => v.getName())
      .join(", ")}`,
  );
}

export async function getGeneratedSchema({
  tsProject,
  zeroSchema,
  zeroSchemaTypeDecl,
  outputFilePath,
}: {
  tsProject: Project;
  zeroSchema: unknown;
  zeroSchemaTypeDecl: readonly [string, ExportedDeclarations];
  outputFilePath: string;
}) {
  const schemaObjectName = "schema";
  const aliasName = "DrizzleConfigSchema";
  const typename = "Schema";

  const zeroSchemaGenerated = tsProject.createSourceFile(outputFilePath, "", {
    overwrite: true,
  });

  const moduleSpecifier =
    zeroSchemaGenerated.getRelativePathAsModuleSpecifierTo(
      zeroSchemaTypeDecl[1].getSourceFile(),
    );

  // Add import for DrizzleConfigSchema
  zeroSchemaGenerated.addImportDeclaration({
    moduleSpecifier,
    namedImports: [{ name: zeroSchemaTypeDecl[0], alias: aliasName }],
    isTypeOnly: true,
  });

  const schemaVariable = zeroSchemaGenerated.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: schemaObjectName,
        initializer: (writer) => {
          const writeValue = (
            value: unknown,
            keys: string[] = [],
            indent = 0,
          ) => {
            const indentStr = " ".repeat(indent);

            if (
              !value ||
              typeof value === "string" ||
              typeof value === "number" ||
              typeof value === "boolean" ||
              Array.isArray(value)
            ) {
              writer.write(JSON.stringify(value));
            } else if (typeof value === "object" && value !== null) {
              writer.write("{");

              const entries = Object.entries(value);

              if (entries.length > 0) {
                writer.newLine();

                for (let i = 0; i < entries.length; i++) {
                  const [key, propValue] = entries[i] ?? [];

                  if (!key) {
                    continue;
                  }

                  writer.write(indentStr + "  " + JSON.stringify(key) + ": ");

                  // Special handling for customType: null
                  if (key === "customType" && propValue === null) {
                    writer.write(
                      `null as typeof ${aliasName}${[...keys, "customType"].map((k) => `["${k}"]`).join("")}`,
                    );
                  } else {
                    writeValue(propValue, [...keys, key], indent + 2);
                  }

                  if (i < entries.length - 1) {
                    writer.write(",");
                  }

                  writer.newLine();
                }

                writer.write(indentStr);
              }

              writer.write("}");
            }
          };

          writeValue(zeroSchema);
          writer.write(` as const`);
        },
      },
    ],
  });

  schemaVariable.addJsDoc({
    description:
      "\nThe Zero schema object.\nThis type is auto-generated from your Drizzle schema definition.",
  });

  const schemaTypeAlias = zeroSchemaGenerated.addTypeAlias({
    name: typename,
    isExported: true,
    type: `typeof ${schemaObjectName}`,
  });

  schemaTypeAlias.addJsDoc({
    description:
      "\nRepresents the Zero schema type.\nThis type is auto-generated from your Drizzle schema definition.",
  });

  zeroSchemaGenerated.formatText();

  const organizedFile = zeroSchemaGenerated.organizeImports();

  const file = organizedFile.getText();

  return `/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero  ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

${file}`;
}
