import { drizzleZeroConfig } from "drizzle-zero";
import * as drizzleSchema from "./drizzle/schema";

export const schema = drizzleZeroConfig(drizzleSchema, {
  tables: {
    user: {
      createdAt: true,
      updatedAt: true,
      id: true,
      name: true,
      partner: true,
      email: true,
      customTypeJson: true,
      customInterfaceJson: true,
      testInterface: true,
      testType: true,
      testExportedType: true,
    },
    medium: {
      createdAt: true,
      updatedAt: true,
      id: true,
      name: true,
    },
    message: {
      createdAt: true,
      updatedAt: true,
      id: true,
      senderId: true,
      mediumId: true,
      body: true,
      metadata: true,
    },
    allTypes: {
      id: true,
      createdAt: true,
      updatedAt: true,
      smallintField: true,
      integerField: true,
      bigintField: true,
      bigintNumberField: true,
      smallSerialField: true,
      serialField: true,
      bigSerialField: true,
      numericField: true,
      decimalField: true,
      realField: true,
      doublePrecisionField: true,
      textField: true,
      charField: true,
      uuidField: true,
      varcharField: true,
      booleanField: true,
      timestampField: true,
      timestampTzField: true,
      timestampModeDate: true,
      timestampModeString: true,
      dateField: true,
      jsonField: true,
      jsonbField: true,
      typedJsonField: true,
      statusField: true,
      optionalSmallint: true,
      optionalInteger: true,
      optionalBigint: true,
      optionalNumeric: true,
      optionalReal: true,
      optionalDoublePrecision: true,
      optionalText: true,
      optionalBoolean: true,
      optionalTimestamp: true,
      optionalJson: true,
      optionalEnum: true,
      optionalVarchar: true,
      optionalUuid: true,
    },
    friendship: {
      acceptingId: true,
      requestingId: true,
      accepted: true,
    },
  },
  manyToMany: {
    user: {
      mediums: ["message", "medium"],
      friends: [
        {
          sourceField: ["id"],
          destTable: "friendship",
          destField: ["requestingId"],
        },
        {
          sourceField: ["acceptingId"],
          destTable: "user",
          destField: ["id"],
        },
      ],
    },
  },
});
