/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero  ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { schema as DrizzleConfigSchema } from "./config/drizzle-zero.config";

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof DrizzleConfigSchema;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    allTypes: {
      name: "allTypes",
      columns: {
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        smallintField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "smallint",
        },
        integerField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "integer",
        },
        bigintField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "bigint",
        },
        bigintNumberField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "bigint_number",
        },
        smallSerialField: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "smallserial",
        },
        serialField: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "serial",
        },
        bigSerialField: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "bigserial",
        },
        numericField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "numeric",
        },
        decimalField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "decimal",
        },
        realField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "real",
        },
        doublePrecisionField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "double_precision",
        },
        textField: {
          type: "string",
          optional: false,
          customType: null as unknown,
          serverName: "text",
        },
        charField: {
          type: "string",
          optional: false,
          customType: null as unknown,
          serverName: "char",
        },
        uuidField: {
          type: "string",
          optional: false,
          customType: null as unknown,
          serverName: "uuid",
        },
        varcharField: {
          type: "string",
          optional: false,
          customType: null as unknown,
          serverName: "varchar",
        },
        booleanField: {
          type: "boolean",
          optional: false,
          customType: null as unknown,
          serverName: "boolean",
        },
        timestampField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "timestamp",
        },
        timestampTzField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "timestamp_tz",
        },
        timestampModeString: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "timestamp_mode_string",
        },
        timestampModeDate: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "timestamp_mode_date",
        },
        dateField: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "date",
        },
        jsonField: {
          type: "json",
          optional: false,
          customType: null as unknown,
          serverName: "json",
        },
        jsonbField: {
          type: "json",
          optional: false,
          customType: null as unknown,
          serverName: "jsonb",
        },
        typedJsonField: {
          type: "json",
          optional: false,
          customType: null as unknown,
          serverName: "typed_json",
        },
        statusField: {
          type: "string",
          optional: false,
          customType: null as unknown,
          serverName: "status",
        },
        optionalSmallint: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "optional_smallint",
        },
        optionalInteger: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "optional_integer",
        },
        optionalBigint: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "optional_bigint",
        },
        optionalNumeric: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "optional_numeric",
        },
        optionalReal: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "optional_real",
        },
        optionalDoublePrecision: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "optional_double_precision",
        },
        optionalText: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "optional_text",
        },
        optionalBoolean: {
          type: "boolean",
          optional: true,
          customType: null as unknown,
          serverName: "optional_boolean",
        },
        optionalTimestamp: {
          type: "number",
          optional: true,
          customType: null as unknown,
          serverName: "optional_timestamp",
        },
        optionalJson: {
          type: "json",
          optional: true,
          customType: null as unknown,
          serverName: "optional_json",
        },
        optionalEnum: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "optional_enum",
        },
        optionalVarchar: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "optional_varchar",
        },
        optionalUuid: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "optional_uuid",
        },
      },
      primaryKey: ["id"],
      serverName: "all_types",
    },
    friendship: {
      name: "friendship",
      columns: {
        requestingId: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        acceptingId: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        accepted: {
          type: "boolean",
          optional: false,
          customType: null as unknown,
        },
      },
      primaryKey: ["requestingId", "acceptingId"],
    },
    medium: {
      name: "medium",
      columns: {
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
      },
      primaryKey: ["id"],
    },
    message: {
      name: "message",
      columns: {
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        senderId: {
          type: "string",
          optional: true,
          customType: null as unknown,
        },
        mediumId: {
          type: "string",
          optional: true,
          customType: null as unknown,
        },
        body: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        metadata: {
          type: "json",
          optional: false,
          customType: null as unknown,
        },
      },
      primaryKey: ["id"],
    },
    user: {
      name: "user",
      columns: {
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        partner: {
          type: "boolean",
          optional: false,
          customType: null as unknown,
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        customTypeJson: {
          type: "json",
          optional: false,
          customType: null as unknown,
          serverName: "custom_type_json",
        },
        customInterfaceJson: {
          type: "json",
          optional: false,
          customType: null as unknown,
          serverName: "custom_interface_json",
        },
        testInterface: {
          type: "json",
          optional: false,
          customType: null as unknown,
          serverName: "test_interface",
        },
        testType: {
          type: "json",
          optional: false,
          customType: null as unknown,
          serverName: "test_type",
        },
        testExportedType: {
          type: "json",
          optional: false,
          customType: null as unknown,
          serverName: "test_exported_type",
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {
    user: {
      mediums: [
        {
          sourceField: ["id"],
          destField: ["senderId"],
          destSchema: "message",
          cardinality: "many",
        },
        {
          sourceField: ["mediumId"],
          destField: ["id"],
          destSchema: "medium",
          cardinality: "many",
        },
      ],
      friends: [
        {
          sourceField: ["id"],
          destField: ["requestingId"],
          destSchema: "friendship",
          cardinality: "many",
        },
        {
          sourceField: ["acceptingId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "many",
        },
      ],
      messages: [
        {
          sourceField: ["id"],
          destField: ["senderId"],
          destSchema: "message",
          cardinality: "many",
        },
      ],
    },
    medium: {
      messages: [
        {
          sourceField: ["id"],
          destField: ["mediumId"],
          destSchema: "message",
          cardinality: "many",
        },
      ],
    },
    message: {
      medium: [
        {
          sourceField: ["mediumId"],
          destField: ["id"],
          destSchema: "medium",
          cardinality: "one",
        },
      ],
      sender: [
        {
          sourceField: ["senderId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "one",
        },
      ],
    },
  },
} as Schema;
